### ISSUE TITLE
Update to Newer API releases: Latest 2.8.0

### ISSUE THREAD

**Issue by kirittanna** [jemutorres/tableau-api-js#2]
https://help.tableau.com/current/api/js_api/en-us/JavaScriptAPI/js_api_concepts_get_API.htm

**Comment by jemutorres** [comment]
Hi @kirittanna,

Thank you for use the npm package.

A new version with Tableau API 2.8.0 has been released in commit c6ef1514fb203397ce8673c174d6da006a3b3535

Regards,
Jesús
