### ISSUE TITLE
TypeError: tableau_api_js__WEBPACK_IMPORTED_MODULE_6__.Viz is not a constructor

### ISSUE THREAD

**Issue by pb-cruxy** [jemutorres/tableau-api-js#3]
On upgrading from 2.6.1 to 2.8.0 we now see an error

"TypeError: tableau_api_js__WEBPACK_IMPORTED_MODULE_6__.Viz is not a constructor"

This looks very similar to the same issue seen on upgrading to 2.6.0 - https://github.com/jemutorres/tableau-api-js/issues/1

Could it be caused by a similar issue with the constructor in 2.8.0?

**Comment by jemutorres** [comment]
Hi @pb-cruxy,

Thank you for use this library. 

Try to update npm version package to 2.8.1 It will fix!

Regards.

**Comment by pb-cruxy** [comment]
Thanks! Perfect.
