### ISSUE TITLE
Update to a new version 2.9.1

### ISSUE THREAD

**Issue by ivan-luxoft** [jemutorres/tableau-api-js#4]
Hello,

There is a new version (2.9.1) on the tableau site:
https://help.tableau.com/current/api/js_api/en-us/JavaScriptAPI/js_api_concepts_get_API.htm

Could you update the npm packages please?

**Comment by jemutorres** [comment]
Hi @ivan-luxoft,

Thank you for use this library!

Try to update npm version package to 2.9.1: https://www.npmjs.com/package/tableau-api-js?activeTab=readme

Regards.
